CREATE OR REPLACE TABLE STG_COVID_COUNTRY AS
SELECT * FROM GLOBAL_COVID_STRATEGIES.INSIGHTS.COVID19_METRICS_BY_COUNTRY;

CREATE OR REPLACE TABLE STG_HOSPITAL AS
SELECT * FROM GLOBAL_COVID_STRATEGIES.INSIGHTS.COVID19_HOSPITAL_METRICS_BY_COUNTRY;

CREATE OR REPLACE TABLE STG_VACCINATION AS
SELECT * FROM GLOBAL_COVID_STRATEGIES.INSIGHTS.COVID19_VACCINATION_METRICS_BY_COUNTRY;

CREATE OR REPLACE TABLE STG_VACCINATION_LIST AS
SELECT * FROM GLOBAL_COVID_STRATEGIES.INSIGHTS.VACCINATION_LIST_BY_COUNTRY;

CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT
    TO_VARCHAR(DATE, 'YYYYMMDD') AS DATE_KEY,
    DATE AS FULL_DATE,
    YEAR(DATE) AS YEAR,
    MONTH(DATE) AS MONTH,
    DAY(DATE) AS DAY,
    WEEK(DATE) AS WEEK
FROM STG_COVID_COUNTRY;

CREATE OR REPLACE TABLE DIM_COUNTRY AS
SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY COUNTRY) AS COUNTRY_KEY,
    COUNTRY AS COUNTRY_NAME,
    ISO_CODE,
    POPULATION,
    TRUE AS IS_CURRENT
FROM STG_COVID_COUNTRY;

CREATE OR REPLACE TABLE DIM_CONTINENT AS
SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY CONTINENT) AS CONTINENT_KEY,
    CONTINENT AS CONTINENT_NAME
FROM STG_COVID_COUNTRY
WHERE CONTINENT IS NOT NULL;

CREATE OR REPLACE TABLE DIM_VACCINE AS
SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY VACCINES) AS VACCINE_KEY,
    VACCINES
FROM STG_VACCINATION_LIST;

CREATE OR REPLACE TABLE FACT_COVID_DAILY AS
WITH base_data AS (
    SELECT
        c.COUNTRY,
        c.DATE,
        c.NEW_CASES,
        c.NEW_DEATHS,
        h.HOSP_PATIENTS AS HOSPITALIZED,
        h.ICU_PATIENTS,
        v.NEW_VACCINATIONS,
        c.CONTINENT
    FROM GLOBAL_COVID_STRATEGIES.INSIGHTS.COVID19_METRICS_BY_COUNTRY c
    LEFT JOIN GLOBAL_COVID_STRATEGIES.INSIGHTS.COVID19_HOSPITAL_METRICS_BY_COUNTRY h
        ON c.COUNTRY = h.COUNTRY
       AND c.DATE = h.DATE
    LEFT JOIN GLOBAL_COVID_STRATEGIES.INSIGHTS.COVID19_VACCINATION_METRICS_BY_COUNTRY v
        ON c.COUNTRY = v.COUNTRY
       AND c.DATE = v.DATE
    WHERE c.DATE BETWEEN '2021-01-01' AND '2021-12-31'
)
SELECT
    ROW_NUMBER() OVER (ORDER BY COUNTRY, DATE) AS FACT_ID,
    COUNTRY,
    DATE,
    CONTINENT,
    NEW_CASES,
    NEW_DEATHS,
    HOSPITALIZED,
    ICU_PATIENTS,
    NEW_VACCINATIONS,
    SUM(NEW_CASES) OVER (PARTITION BY COUNTRY ORDER BY DATE) AS CUMULATIVE_CASES,
    AVG(NEW_CASES) OVER (
        PARTITION BY COUNTRY 
        ORDER BY DATE 
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS AVG_7D_CASES,
    LAG(NEW_CASES) OVER (PARTITION BY COUNTRY ORDER BY DATE) AS PREV_DAY_CASES,
    RANK() OVER (PARTITION BY DATE ORDER BY NEW_CASES DESC) AS DAILY_CASE_RANK
FROM base_data;

SELECT COUNT(*) FROM FACT_COVID_DAILY;

SELECT
    COUNTRY,
    MAX(CUMULATIVE_CASES) AS TOTAL_CASES
FROM FACT_COVID_DAILY
GROUP BY COUNTRY
ORDER BY TOTAL_CASES DESC;